default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: petz_development
  username: carlavaldivia
  password:
  host: localhost
  port: 5432

test:
  <<: *default
  database: petz_test
  username: carlavaldivia
  password:
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
